
package ssm.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CordovaWebService", targetNamespace = "http://webservice.ssm/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CordovaWebService {


    /**
     * 
     * @param name
     * @param pwd
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.ssm/CordovaWebService/cordovaAndiroLoginRequest", output = "http://webservice.ssm/CordovaWebService/cordovaAndiroLoginResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservice.ssm/CordovaWebService/cordovaAndiroLogin/Fault/Exception")
    })
    public String cordovaAndiroLogin(
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "pwd", partName = "pwd")
        String pwd)
        throws Exception_Exception
    ;

}
