
package ssm.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CordovaWebServiceImplService", targetNamespace = "http://webservice.ssm/", wsdlLocation = "http://192.168.1.152:9081/Service/CordovaWebService?wsdl")
public class CordovaWebServiceImplService
    extends Service
{

    private final static URL CORDOVAWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CORDOVAWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CORDOVAWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.ssm/", "CordovaWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.152:9081/Service/CordovaWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CORDOVAWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CORDOVAWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CordovaWebServiceImplService() {
        super(__getWsdlLocation(), CORDOVAWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CordovaWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CORDOVAWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CordovaWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CORDOVAWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CordovaWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CORDOVAWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CordovaWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CordovaWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CordovaWebService
     */
    @WebEndpoint(name = "CordovaWebServiceImplPort")
    public CordovaWebService getCordovaWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.ssm/", "CordovaWebServiceImplPort"), CordovaWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CordovaWebService
     */
    @WebEndpoint(name = "CordovaWebServiceImplPort")
    public CordovaWebService getCordovaWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ssm/", "CordovaWebServiceImplPort"), CordovaWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CORDOVAWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CORDOVAWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CORDOVAWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
